[global]
# Streamlit configuration for Bharat Voices

# Development mode
developmentMode = false

# Show warning when running in development mode
showWarningOnDirectExecution = false

[server]
# Server settings
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

# Allow running on all interfaces for public access
headless = true
runOnSave = false
allowRunOnSave = false

[browser]
# Browser settings
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
# UI Theme
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[logger]
# Logging settings
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
